# Generated by Django 4.1.3 on 2022-12-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="date_create",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="icon_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
